version: '3.1'

services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: jay
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /data/live
    ports:
      - 5432:5432
    networks:
      - caseStudy
    volumes:
      - live:/data/live
      - ./sql:/docker-entrypoint-initdb.d
    restart: unless-stopped

networks:
  caseStudy:
    driver: bridge

volumes:
  live:
